apiVersion: v1
kind: Namespace
metadata:
  name: k6-demo
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: k6
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
spec: {}
status: {}
