apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: k6-demo
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
spec:
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
